tab1vars <- c(
  "num_region",
  # Clinical characteristics
  "num_age",
  "num_age_cat",
  "num_dmgender",
  "num_dmBmi",
  "num_dmBmi_cat",
  "num_dmEthnic",
  "num_dmhome",
  "num_dmBp1",
  "num_dmBp2",
  "num_dmBpm",
  "num_Hypop",
  "num_dmHF",
  "d_HFdiagnosis",
  "num_dmEtio",
  "num_dmEtio_c1",
  "num_dmSmoking_cat",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmApn",
  "num_dmStroke",
  "num_dmHyChol",
  "num_dmHepa",
  "num_dmDepr",
  "num_dmAfib",
  "num_dmAfib_c1",
  "num_dmHT",
  "num_dmMi",
  "num_dmPci",
  "num_dmCabg",
  "num_dmValve",
  "num_dmPvd",
  "num_dmVte",
  # "num_dmThy",
  "num_dmDis",
  "num_Nyha",
  "num_Mr",
  "num_Hb",
  "num_Nt",
  "num_CKDEPI"
)

tab2vars <- c(
  "num_Ecg",
  "num_Ryth_c1",
  "num_QrsD",
  "num_Qt",
  "num_Lbbb",
  "num_Lvh2",
  "num_Xr",
  "num_Xpu",
  "num_Xen",
  "num_Xal",
  "num_Echo",
  "num_Ef",
  "num_Ef_cat",
  "num_Lvdd",
  "num_Lvh",
  # "num_Ladim",
  "num_Rsp",
  "num_MitReg",
  "num_AorSte",
  "num_AorReg",
  "num_TriCus",
  "num_ExInab",
  "num_Cycle",
  "num_Tread",
  "num_VO2",
  "num_Walk",
  "num_Hol",
  # "num_Hr",
  # "num_Pvc",
  "num_Uvt",
  "num_Svt",
  # "num_Afib",

  "num_Cora",
  "num_Cct",
  "num_Pci",
  "num_Eps",
  "num_Transab",
  "num_Cardiov",
  "num_RhCath",
  "num_Mysc",
  "num_EndBi",
  "num_Iapb",
  "num_Crt",
  "num_Icd",
  "num_Score"
)

tabmedvars <- c(
  "num_mdACEp",
  "num_mdACE_after",
  "f1_ACE",
  "num_mdATp",
  "num_mdAT_after",
  "f1_AT",
  "num_mdARNIp",
  "num_mdARNI_after",
  "f1_ARNI",
  "num_mdALp",
  "num_mdAL_after",
  "f1_AL",
  "num_mdBBp",
  "num_mdBB_after",
  "f1_BB"
)
