tab1vars <- c(
  "num_region",
  "num_dmPtype",
  # Clinical characteristics
  "num_age",
  "num_age_cat",
  "num_dmgender",
  "num_dmBmi",
  "num_dmBmi_cat",
  "num_dmEthnic",
  "num_dmhome",
  "num_dmBp1",
  "num_dmBp2",
  "num_dmBpm",
  "per_congestion",
  "pulm_congestion",
  "num_Hypop",
  "num_dmHF",
  "d_HFdiagnosis",
  "num_dmEtio",
  "num_dmEtio_c1",
  "num_dmSmoking_cat",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmApn",
  "num_dmStroke",
  "num_dmHyChol",
  "num_dmHepa",
  "num_dmDepr",
  "num_dmAfib",
  "num_dmAfib_c1",
  "num_dmHT",
  "num_dmMi",
  "num_dmPci",
  "num_dmCabg",
  "num_dmValve",
  "num_dmPvd",
  "num_dmVte",
  # "num_dmThy",
  "num_dmDis",
  "num_Nyha",
  "num_Ef",
  "num_Ef_cat",
  "num_dmEflp",
  "num_dmEflp_cat",
  # "num_Mr",
  # "num_Hb",
  "num_MitReg",
  "num_Nt",
  "num_CKDEPI"
)

tab2vars <- c(
  "num_Ecg",
  # "num_Ryth_c1",
  # "num_QrsD",
  # "num_Qt",
  # "num_Lbbb",
  # "num_Lvh2",
  "num_Xr",
  # "num_Xpu",
  # "num_Xen",
  # "num_Xal",
  "num_Echo",
  # "num_Lvdd",
  # "num_Lvh",
  # "num_Ladim",
  # "num_Rsp",

  # "num_AorSte",
  # "num_AorReg",
  # "num_TriCus",
  "num_ExInab",
  # "num_Cycle",
  # "num_Tread",
  # "num_VO2",
  # "num_Walk",
  "num_Hol",
  # "num_Hr",
  # "num_Pvc",
  # "num_Uvt",
  # "num_Svt",
  # "num_Afib",

  "num_Cora",
  "num_Cct",
  "num_Pci",
  "num_Eps",
  "num_Transab",
  "num_Cardiov",
  "num_RhCath",
  "num_Mysc",
  "num_EndBi",
  "num_Iapb",
  "num_Crt",
  "num_Icd",
  "num_Score"
)

tabmedvars <- c(
  "d_rasi_prior",
  "d_rasiarni_prior",
  "d_rasiarnidosetarget_prior",
  "d_rasi_after",
  "d_rasiarni_after",
  "d_rasiarnidosetarget_after",
  "f1_rasi",
  "f1_rasiarni",
  "f1_rasiarnidosetarget",
  "num_mdACEp",
  "num_mdACE_after",
  "num_mdACE_aftern",
  "f1_ACE",
  "num_f1ACEhn",
  "num_mdATp",
  "num_mdAT_after",
  "num_mdAT_aftern",
  "f1_AT",
  "num_f1AThn",
  "num_mdARNIp",
  "num_mdARNI_after",
  "num_mdARNI_aftern",
  "f1_ARNI",
  "num_f1ARNIn",
  "num_mdALp",
  "num_mdAL_after",
  "num_mdAL_aftern",
  "f1_AL",
  "num_f1ALhn",
  "num_mdBBp",
  "d_BBdosetarget_prior",
  "num_mdBB_after",
  "num_mdBB_aftern",
  "num_mdBBdo_aftercn",
  "d_BBdosetarget_after",
  "f1_BB",
  "num_f1BBhn",
  "f1_BBdosetarget"
)

modvars <- c(
  "num_age_cat",
  "num_dmgender",
  "num_dmBmi_cat",
  "num_dmhome",
  "num_dmBp1",
  "num_dmBpm",
  "per_congestion",
  "pulm_congestion",
  "num_Hypop",
  "d_HFdiagnosis",
  "num_dmEtio_c1",
  "num_dmSmoking_cat",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmApn",
  "num_dmStroke",
  "num_dmHyChol",
  "num_dmHepa",
  "num_dmDepr",
  "num_dmAfib_c1",
  "num_dmHT",
  "num_dmMi",
  "num_dmPci",
  "num_dmCabg",
  "num_dmValve",
  "num_dmPvd",
  "num_dmVte",
  "num_dmDis",
  "num_Nyha",
  "num_Ef_cat",
  "num_MitReg",
  "num_Nt",
  "num_CKDEPI"
)
