tab1vars <- c(
  "num_region",
  "num_dmPtype",
  # Clinical characteristics
  "num_age",
  "num_age_cat",
  "num_dmgender",
  "num_dmBmi",
  "num_dmBmi_cat",
  "num_dmEthnic",
  "num_dmhome_cat",
  "num_dmBp1",
  "num_dmBp1_cat",
  "num_dmBp2",
  "num_dmBpm",
  "num_dmBpm_cat",
  "per_congestion",
  "pulm_congestion",
  "num_Hypop",
  "num_dmHF",
  "d_HFdiagnosis",
  "num_dmEtio",
  "num_dmEtio_c1",
  "num_dmSmoking_cat",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmApn",
  "num_dmStroke",
  "num_dmHyChol",
  "num_dmHepa",
  "num_dmDepr",
  "num_dmAfib",
  "num_dmAfib_c1",
  "num_dmHT",
  "num_dmMi",
  "num_dmPci",
  "num_dmCabg",
  "num_dmValve",
  "num_dmPvd",
  "num_dmVte",
  # "num_dmThy",
  "num_dmDis",
  "num_Nyha",
  "num_Nyha_cat",
  "num_Ef",
  "num_Ef_cat",
  "num_dmEflp",
  "num_dmEflp_cat",
  # "num_Mr",
  # "num_Hb",
  "num_MitReg",
  "num_Nt",
  "num_Nt_cat",
  "num_CKDEPI",
  "num_CKDEPI_cat"
)

tabmedvars <- c(
  "d_rasiarni_after",
  "d_rasiarnidosetarget_after",
  "f1_rasiarni",
  "f1_rasiarnidosetarget",
  "num_mdAL_after",
  "d_ALdosetarget_after",
  "f1_AL",
  "f1_ALdosetarget",
  "num_mdBB_after",
  "d_BBdosetarget_after",
  "f1_BB",
  "f1_BBdosetarget",
  "num_Crt",
  "num_Icd"
)

modvars <- c(
  "num_dmPtype",
  "num_age_cat",
  "num_dmgender",
  "num_dmBmi_cat",
  "num_dmhome_cat",
  "num_dmBp1_cat",
  "num_dmBpm_cat",
  "num_Nt_cat",
  "num_CKDEPI_cat",
  "per_congestion",
  "pulm_congestion",
  "num_Hypop",
  "d_HFdiagnosis",
  "num_dmEtio_c1",
  "num_dmSmoking_cat",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmApn",
  "num_dmStroke",
  "num_dmHyChol",
  "num_dmHepa",
  "num_dmDepr",
  "num_dmAfib_c1",
  "num_dmHT",
  "num_dmMi",
  "num_dmPci",
  "num_dmCabg",
  "num_dmValve",
  "num_dmPvd",
  "num_dmVte",
  "num_dmDis",
  "num_Nyha_cat",
  "num_Ef_cat",
  "num_MitReg"
)

modvarscox <- modvars
modvarscox[modvarscox == "num_dmPtype"] <- "strata(num_dmPtype)"
