```{r km, cache=cacheon}

kmfunc <- function(time, event, eventname, eventrec, yposplus = rep(0.015, 2)) {
  fits <- survfit(formula(paste0("Surv(", time, ",", event, "== 1) ~ num_dmRCT")),
    data = edata %>% filter(survpop)
  )

  # cox model
  amod <- with(imp, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 1) ~ num_dmRCT + ", paste(modvarscox, collapse = " + "), " + strata(num_nation)"
  ))))

  asmod <- summary(pool(amod))

  hrprint <- paste0(
    fn(exp(asmod$estimate[1]), dig = 2),
    " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 2),
    "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 2), "), ",
    fn(asmod$p.value[1], dig = 3, p = TRUE)
  )

  # c(bottom, left, top, right)
  cexmy <- 1.2
  par(mar = c(6.5, 6, 1, 1.5) + 0.1)

  plots <- plot(fits,
    fun = "event",
    ylab = paste0(eventname, " (%)"),
    yscale = 100,
    xscale = 30.5,
    col = global_cols[c(8, 3)],
    mark.time = FALSE,
    bty = "n",
    xlim = c(0, 12 * 30),
    ylim = c(0, 0.35),
    xlab = "Follow-up (months)",
    cex.lab = cexmy,
    axes = F,
    lwd = 4,
    lty = c(1, 2),
    xaxs = "i", yaxs = "i"
  )

  axis(2, seq(0, 0.35, 0.05), c(seq(0, 30, 5), 100), las = 2, cex.axis = cexmy)
  axis(1, at = seq(0, 12, 2) * 30, seq(0, 12, 2), cex.axis = cexmy)
  axis.break(2, 0.325, style = "slash")

  ypos <- 1 - summary(fits, 9 * 30, extend = T)$surv

  ylabs <- bind_cols(
    ypos = ypos,
    ytext = c("No RCT", "RCT")
  ) %>%
    arrange(ypos)

  text(ylabs$ypos[1] - yposplus[1], x = 9 * 30, ylabs$ytext[1], pos = 4, cex = cexmy)
  text(ylabs$ypos[2] + yposplus[2], x = 9 * 30, ylabs$ytext[2], pos = 2, cex = cexmy)

  text(y = 0.28, x = 4 * 30, "Adjusted HR (95% CI), p-value", cex = cexmy, adj = 0.5)
  text(y = 0.26, x = 4 * 30, hrprint, cex = cexmy, adj = 0.5)

  mtext("No. at risk", side = 1, line = 3.7, at = -60, adj = 0, cex = cexmy, font = 2)
  mtext("No RCT", side = 1, line = 4.7, at = -60, adj = 0, cex = cexmy)
  mtext("RCT", side = 1, line = 5.7, at = -60, adj = 0, cex = cexmy)

  nrisk <- summary(fits, seq(0, 12, 2) * 30, extend = T)$n.risk

  axis(1, at = seq(0, 12, 2) * 30, labels = nrisk[1:7], line = 3.7, tick = FALSE, cex.axis = cexmy)
  axis(1, at = seq(0, 12, 2) * 30, labels = nrisk[8:14], line = 4.7, tick = FALSE, cex.axis = cexmy)
}
```

```{r kmdeath, fig.cap="1-KM All-cause mortality", cache=cacheon, dependson="km", fig.width=8, fig.height=7}
kmfunc(
  time = "outtime_death",
  event = "out_death",
  eventname = "All-cause mortality"
)
```

```{r km1hfhosp, fig.cap="First HF hospitalization", cache=cacheon, dependson="km", fig.width=8, fig.height=7}
kmfunc(
  time = "outtime_hosphf",
  event = "out_hosphf",
  eventname = "First HF hospitalisation"
)
```
