```{r outtab, cache=cacheon}
survfunc <- function(time, event, eventname, data) {
  out <- data.frame(matrix(NA, ncol = 4, nrow = 3))

  out[1, 1] <- eventname
  colnames(out) <- c("Outcome", "Model", levels(edata$num_dmRCT))

  ## incidence rate
  out[1, 2] <- "Incidence"

  ev <- data %>%
    group_by(num_dmRCT) %>%
    summarise(
      ev = sum(!!sym(event) == 1),
      .groups = "rowwise"
    )

  s <- data %>%
    group_by(num_dmRCT) %>%
    summarise(
      s = sum(!!sym(time) / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s / 100)

  out[1, 3:4] <- paste0(
    ev$ev, ", ",
    fn(s$s, dig = 0), ", ",
    fn(r$rate, dig = 1), " (",
    fn(r$lower, dig = 1), "-",
    fn(r$upper, dig = 1), ")"
  )

  # cox regressions

  ## crude

  out[2, 2] <- "Crude HR (95% CI), p-value"

  mod <- coxph(formula(paste0("Surv(", time, ",", event, "== 1) ~ num_dmRCT + strata(num_nation)")),
    data = data
  )

  smod <- summary(mod)
  out[2, 3:4] <- c("ref", paste0(
    fn(smod$conf.int[1, 1], dig = 2),
    " (", fn(smod$conf.int[1, 3], dig = 2),
    "-", fn(smod$conf.int[1, 4], dig = 2), "), ",
    fn(smod$coef[1, "Pr(>|z|)"], dig = 3, p = TRUE)
  ))

  ## adjusted individual covariates

  out[3, 2] <- "Adjusted HR (95% CI), p-value"

  amod <- with(imp, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 1) ~ num_dmRCT + ", paste(modvarscox, collapse = " + "), " + strata(num_nation)"
  ))))

  asmod <- summary(pool(amod))

  out[3, 3:4] <- c("ref", paste0(
    fn(exp(asmod$estimate[1]), dig = 2),
    " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 2),
    "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 2), "), ",
    fn(asmod$p.value[1], dig = 3, p = TRUE)
  ))
  return(out)
}
```

```{r outtaball, cache=cacheon, dependson="outtab"}
death <- survfunc(
  time = "outtime_death",
  event = "out_death",
  eventname = "All-cause mortality",
  data = edata %>% filter(survpop)
)
hosphf <- survfunc(
  time = "outtime_hosphf",
  event = "out_hosphf",
  eventname = "First HF hospitalisation",
  data = edata %>% filter(survpop)
)

outall <- rbind(
  death,
  hosphf
)

write.xlsx(outall, paste0("./output/tabs/Outcomes by TP_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

footnote(default_kable(outall,
  font_size = 6,
  caption = "Outcomes by TP"
),
general = c(
  "Incidence =  no events, sum py, rate/100py (95% CI)."
)
)
```
