```{r outsub, cache=cacheon}
survsubfunc <- function(time, event, xvar, xvarname) {
  levs <- levels(edata %>% pull(!!sym(xvar)))

  out <- data.frame(matrix(NA, ncol = 6, nrow = length(levs) + 1))
  colnames(out) <- c("Subgroup", "HR (95% CI)", "p", "coef", "lci", "uci")

  out[1, 1] <- xvarname

  for (i in seq_along(levs)) {
    out[1 + i, 1] <- paste0("  ", levs[i])

    ## adjusted individual covariates
    amod <- with(imp, coxph(formula(paste0(
      "Surv(", time, ",", event, " == 1) ~ num_dmRCT * relevel(", xvar, ", ref = '", levs[i], "') + ",
      paste(modvarscox[modvarscox != xvar], collapse = " + ")
    ))))

    ## df the number of events minus the regression coefficients.
    ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
    asmod <- summary(pool(amod,
      dfcom =
        (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
    ))


    out[1 + i, 2] <- paste0(
      fn(exp(asmod$estimate[1]), dig = 2),
      " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 2),
      "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 2), ")"
    )

    out[1 + i, 4] <- asmod$estimate[1]
    out[1 + i, 5] <- asmod$estimate[1] - global_z05 * asmod$std.error[1]
    out[1 + i, 6] <- asmod$estimate[1] + global_z05 * asmod$std.error[1]

    if (i == 1) {
      if (length(levs) == 2) {
        out[1, 3] <- fn(last(asmod$p.value), dig = 3, p = TRUE)
      } else {
        amodnoint <- with(imp, coxph(formula(paste0(
          "Surv(", time, ",", event, " == 1) ~ num_dmRCT + relevel(", xvar, ", ref = '", levs[i], "') + ",
          paste(modvarscox[modvarscox != xvar], collapse = " + ")
        ))))

        int <- D1(amod, amodnoint)

        out[1, 3] <- fn(int$result[4], dig = 3, p = TRUE)
      }
    }
  }
  return(out)
}

survsubfunc2 <- function(time2, event2) {
  forestdata <- survsubfunc(
    time = time2,
    event = event2,
    xvar = "num_dmPtype",
    xvarname = "Location"
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "d_HFdiagnosis",
      xvarname = "HF History (months)"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_age_cat",
      xvarname = "Age (years)"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_Ef_cat",
      xvarname = "LVEF (%)"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmgender",
      xvarname = "Sex"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_CKDEPI_cat",
      xvarname = "eGFR (ml/min/1.73 m2)"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmBp1_cat",
      xvarname = "Systolic BP (mmHg)"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_Nyha_cat",
      xvarname = "NYHA class"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmHT",
      xvarname = "Hypertension"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmDiab_c1",
      xvarname = "Diabetes"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmCopd",
      xvarname = "COPD"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmApn",
      xvarname = "Sleep apnea"
    )
  )
  forestdata <- rbind(
    forestdata,
    forestdata <- survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmAfib_c1",
      xvarname = "Atrial Fibrillation/Flutter"
    )
  )
}
```

```{r outsubplot, cache=cacheon, dependson="outsub"}
plotforest <- function(forestdata) {
  cextext <- 1

  minmy <- round(exp(min(forestdata$lci, na.rm = T)), 1)
  maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)

  # c(bottom, left, top, right)
  par(mar = c(3, 17, 0, 0.5) + 0.2)


  plot(rev(forestdata$coef), 1:nrow(forestdata),
    cex = 2,
    xlim = c(
      log(minmy),
      log(maxmy)
    ),
    xlab = NA,
    ylim = c(1, nrow(forestdata)),
    axes = FALSE,
    ylab = NA,
    main = NA,
    type = "p",
    pch = 22,
    bg = global_cols[3],
    col = global_cols[3]
  )

  for (i in 1:nrow(forestdata)) {
    if (!is.na(rev(forestdata$lci)[i])) {
      matplot(c(rev(forestdata$lci)[i], rev(forestdata$uci)[i]), c(i, i),
        type = "l", add = TRUE, col = global_cols[3], lwd = 2
      )
    }
  }

  matplot(c(log(1), log(1)), c(-1, nrow(forestdata)), type = "l", lwd = 1, lty = 1, add = TRUE, col = 1)

  axismy <- seq(minmy, maxmy, 0.1)
  axismy2 <- axismy
  axismy2[!axismy %in% c(minmy, maxmy)] <- NA

  axis(1,
    cex.axis = cextext, at = log(c(axismy, 1)),
    labels = c(axismy2, 1)
  )

  axis(2,
    at = nrow(forestdata) + 1,
    labels = "Subgroup",
    cex.axis = cextext, tick = FALSE, las = 2, line = 16, hadj = 0, font = 2
  )
  forestdata <- forestdata %>%
    mutate(
      Subgroup = str_replace_all(Subgroup, ">=", "\u2265"),
      Subgroup = str_replace_all(Subgroup, "<=", "\u2264"),
      Subgroup = str_replace_all(Subgroup, "<12", "12"),
      Subgroup = str_replace_all(Subgroup, ">12", "12")
    )

  axis(2,
    at = 1:nrow(forestdata),
    labels = c(rev(forestdata$Subgroup)),
    cex.axis = cextext, tick = FALSE, las = 2, line = 16, hadj = 0
  )

  axis(2,
    at = nrow(forestdata) + 1,
    labels = "HR (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = 6, hadj = 0.5, font = 2
  )
  axis(2,
    at = 1:nrow(forestdata),
    labels = rev(forestdata$`HR (95% CI)`),
    cex.axis = cextext, tick = FALSE, las = 2, line = 6, hadj = 0.5
  )

  axis(2,
    at = nrow(forestdata) + 1,
    labels = "P interaction",
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5, font = 2
  )
  axis(2,
    at = 1:nrow(forestdata),
    labels = rev(forestdata$p),
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5
  )

  axis(1,
    at = (log(maxmy) + log(minmy)) / 2, cex.axis = cextext,
    labels = "HR (95% CI)", line = 1, tick = FALSE
  )
}
```

```{r outsubdeath, cache=cacheon, dependson="outsub"}
death <- survsubfunc2(
  time2 = "outtime_death",
  event2 = "out_death"
)
```

```{r forestdeath, cache=cacheon, dependson=c("outsubdeath", "outsubplot"), fig.cap="Subgroups Death", fig.width=5, fig.height=10}
plotforest(death)
```

```{r outsubhfh, cache=cacheon, dependson="outsub"}
hosphf <- survsubfunc2(
  time2 = "outtime_hosphf",
  event2 = "out_hosphf"
)
```

```{r foresthfh, cache=cacheon, dependson=c("outsubdeath", "outsubplot"), fig.cap="Subgroups HFH", fig.width=5, fig.height=10}
plotforest(hosphf)
```
