```{r tab1, cache=cacheon}

tab1func <- function(data, tabvars = tab1vars,
                     tabnamebase = "Baseline characteristics by trial participation - ",
                     tabname) {
  tab <- print(
    CreateTableOne(
      vars = tabvars,
      data = data,
      strata = "num_dmRCT"
    ),
    smd = FALSE,
    missing = TRUE,
    printToggle = FALSE,
    nonnormal = tabvars,
    test = TRUE,
    catDigits = 1,
    contDigits = 1,
    explain = FALSE,
    noSpaces = TRUE
  )
  tab <- as_tibble(cbind(var = rownames(tab), tab)) %>%
    select(-test) %>%
    select(var, Missing, everything())

  tab <- tab %>%
    # to get labs in place
    mutate(
      var_tmp = str_split(var, " = ", simplify = TRUE)[, 1],
      val_tmp = str_split(var, " = ", simplify = TRUE)[, 2],
      val_tmp = if_else(val_tmp == "Yes", "", val_tmp)
    )

  tab <- left_join(tab,
    esclab %>%
      select(variable, label),
    by = c("var_tmp" = "variable")
  ) %>%
    mutate(
      Variable = coalesce(label, var_tmp),
      Variable = if_else(val_tmp != "",
        paste0(Variable, " ", val_tmp),
        Variable
      )
    )

  tabnamebasexls <- str_replace(tabnamebase, "<=", "below")
  tabnamebasexls <- str_replace(tabnamebase, ">=", "above")
  write.xlsx(tab %>%
    select(Variable, Missing:p), paste0("./output/tabs/tab1_", tabnamebasexls, tabname, "_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

  # footnotes
  tab <- tab %>%
    mutate(
      footnote1 = if_else(var_tmp %in% modvars, footnote_marker_symbol(1), "")
    ) %>%
    unite(footnote, starts_with("footnote"), sep = "") %>%
    mutate(
      # so no probs
      Variable = sanitize_text(Variable),
      Variable = paste0(Variable, footnote),

      # space in Latex output (fix this other way?)
      Variable = sub("  ", ". ", Variable)
    ) %>%
    select(Variable, Missing:p)

  colnames(tab) <- sanitize_text(c(
    "Variable", "Missing (%)", levels(edata %>% pull(num_dmRCT)), "p-value"
  ))

  footnote(
    default_kable(tab,
      font_size = 6,
      caption = paste0(tabnamebase, tabname),
      longtable = TRUE,
      escape = FALSE
    ), # %>%
    # landscape(),
    general = c(
      "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test."
    ),
    symbol = c("Included in imputation, logistic and cox regression models")
  )
}
```

```{r tab1surv, cache=cacheon, dependson="tab1"}
tab1func(data = edata %>% filter(survpop), tabname = "Analysis population")
```

\clearpage

```{r tab1all, cache=cacheon, dependson="tab1"}
tab1func(data = edata, tabname = "All, for supplementary")
```

\clearpage

```{r tabmedsurv, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata %>% filter(survpop),
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - ",
  tabname = "Analysis population"
)
```

\clearpage

```{r tabmedall, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata,
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - ",
  tabname = "All, for supplementary"
)
```

\clearpage

```{r tabmedsurvref, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata %>% filter(survpop & num_Ef_cat == "<=40%"),
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - LVEF <=40 - ",
  tabname = "Analysis population"
)
```

\clearpage

```{r tabmedallref, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata %>% filter(num_Ef_cat == "<=40%"),
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - LVEF <=40 - ",
  tabname = "All, for supplementary"
)
```

\clearpage

```{r tabmedsurvmref, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata %>% filter(survpop & num_Ef_cat == "41-49%"),
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - LVEF 41-49 - ",
  tabname = "Analysis population"
)
```

\clearpage

```{r tabmedallmref, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata %>% filter(num_Ef_cat == "41-49%"),
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - LVEF 41-49 - ",
  tabname = "All, for supplementary"
)
```

\clearpage

```{r tabmedsurvpef, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata %>% filter(survpop & num_Ef_cat == ">=50%"),
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - LVEF >=50 - ",
  tabname = "Analysis population"
)
```

\clearpage

```{r tabmedallpef, cache=cacheon, dependson="tab1"}
tab1func(
  data = edata %>% filter(num_Ef_cat == ">=50%"),
  tabvars = tabmedvars,
  tabnamebase = "Medications by trial participation - LVEF >=50 - ",
  tabname = "All, for supplementary"
)
```
