```{r tabmed, cache=cacheon}

tab1func <- function(data, tabname) {
  tab <- print(
    CreateTableOne(
      vars = tabmedvars,
      data = data,
      strata = "num_dmRCT"
    ),
    smd = FALSE,
    missing = TRUE,
    printToggle = FALSE,
    nonnormal = tabmedvars,
    test = TRUE,
    catDigits = 1,
    contDigits = 1,
    explain = FALSE,
    noSpaces = TRUE
  )
  tab <- as_tibble(cbind(var = rownames(tab), tab)) %>%
    select(-test) %>%
    select(var, Missing, everything())

  tab <- tab %>%
    # remove = Yes
    mutate(across(everything(), str_replace_all, fixed(" = Yes"), ""))

  tab <- left_join(tab,
    esclab %>%
      select(variable, label),
    by = c("var" = "variable")
  ) %>%
    mutate(
      Variable = coalesce(label, var)
    )

  tab <- tab %>%
    mutate(
      # so no probs
      Variable = sanitize_text(Variable),

      # space in Latex output (fix this other way?)
      Variable = sub("  ", ". ", Variable)
    ) %>%
    select(Variable, Missing:p)

  colnames(tab) <- sanitize_text(c(
    "Variable", "Missing (%)", levels(edata %>% pull(num_dmRCT)), "p-value"
  ))

  write.xlsx(tab, paste0("./output/tabs/tabmed_", tabname, "_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = TRUE)

  footnote(
    default_kable(tab,
      font_size = 6,
      caption = paste0("Medications by trial participation - ", tabname),
      longtable = TRUE,
      escape = FALSE
    ), # %>%
    # landscape(),
    general = c(
      "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [q1-q3] and tested with Kruskal-Wallis test.",
      "Follow-up medication will only be available for persons not lost to follow-up and alive at follow-up."
    )
  )
}
```

```{r tabmedall, cache=cacheon, dependson="tab1"}
tab1func(data = edata, tabname = "All")
```

\clearpage

```{r tabmedallin, cache=cacheon, dependson="tab1"}
tab1func(data = edata %>% filter(num_dmPtype == "Hospital"), tabname = "All - inpatients")
```

\clearpage

```{r tabmedallout, cache=cacheon, dependson="tab1"}
tab1func(data = edata %>% filter(num_dmPtype == "Outpatient"), tabname = "All - outpatients")
```

\clearpage

```{r tabmedsurv, cache=cacheon, dependson="tab1"}
tab1func(data = survdata, tabname = "Not lost to follow-up and alive and discharge (used in long-term outcome analysis)")
```

\clearpage

```{r tabmedsurvin, cache=cacheon, dependson="tab1"}
tab1func(
  data = survdata %>% filter(num_dmPtype == "Hospital"),
  tabname = "Not lost to follow-up and alive and discharge (used in long-term outcome analysis) - inpatients"
)
```

\clearpage

```{r tabmedsurvout, cache=cacheon, dependson="tab1"}
tab1func(
  data = survdata %>% filter(num_dmPtype == "Outpatient"),
  tabname = "Not lost to follow-up and alive and discharge (used in long-term outcome analysis) - outpatients"
)
```
